# action.yml
name: 'Teste do Maurício'

on: [push]
jobs:
  docker-playground-build:
    runs-on: ubuntu-latest
    name: A job to docker build
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
        # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./app
          # Note: tags has to be all lower-case
          tags: ghcr.io/maucarvalho/docker-playground:latest
          # build on feature branches, push only on main branch
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}